version: '3.3'
services:
  postgres:
    image: "postgres:9.4"
    container_name: open-lmis-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p@ssw0rd
      - POSTGRES_DB=open_lmis
    ports:
      - 5432:5432

  open-lmis:
    image: siglus/open-lmis-portal:latest-hotfix
    container_name: open-lmis-portal
    command: sh -c '/scripts/run/wait-for-postgres.sh open-lmis-db sh /scripts/run/start.sh'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p@ssw0rd
      - POSTGRES_HOST=open-lmis-db
      - POSTGRES_DB=open_lmis
      - APP_URL=http://localhost:8080
    ports:
      - 8081:8080
