version: '3.3'
services:
  postgres:
    image: "postgres:9.4"
    container_name: open-lmis-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresPwd
      - POSTGRES_DB=open_lmis
    ports:
      - 5432:5432

  test-runner:
    image: siglus/test-runner:1.0.0
    container_name: test-runner
    privileged: true
    volumes:
      - ../:/lmis-moz-mobile
    working_dir: /lmis-moz-mobile
    command: /bin/sh -c 'tail -f /dev/null'
    environment:
      - KSTOREPWD=!EBus&tre46A
      - KEYPWD=!EBus&tre46A

  open-lmis:
    image: siglus/open-lmis-portal:latest
    container_name: open-lmis-portal
    command: sh -c '/scripts/run/wait-for-postgres.sh open-lmis-db sh /scripts/run/start.sh'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgresPwd
      - POSTGRES_HOST=open-lmis-db
      - POSTGRES_DB=open_lmis
      - APP_URL=http://localhost:8080
    ports:
      - 8081:8080
